/**
 * @file orxExtensions.h
 * !! This file is automatically generated by init, do not modify manually. !!
 * @date 26-Oct-2025
 */

#ifndef _orxEXTENSIONS_H_
#define _orxEXTENSIONS_H_

void InitExtensions()
{
}

void ExitExtensions()
{
}

void BootstrapExtensions()
{
  // Add config storage to find the initial config file
  orxResource_AddStorage(orxCONFIG_KZ_RESOURCE_GROUP, "../data/config", orxFALSE);
}

#endif // _orxEXTENSIONS_H_
